# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bcms_polling}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BrowserMedia"]
  s.date = %q{2011-02-23}
  s.description = %q{Allows for user feedback via short polling questions.}
  s.email = %q{github@browsermedia.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "COPYRIGHT.txt",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "app/controllers/cms/polls_controller.rb",
    "app/controllers/polling_controller.rb",
    "app/helpers/cms/polls_helper.rb",
    "app/models/poll.rb",
    "app/models/poll_response.rb",
    "app/views/cms/polls/_form.html.erb",
    "app/views/cms/polls/render.html.erb",
    "app/views/polling/results.html.erb",
    "db/migrate/20110216195733_create_polls.rb",
    "doc/README_FOR_APP",
    "lib/bcms_polling.rb",
    "lib/bcms_polling/routes.rb",
    "public/bcms/polling/README",
    "public/bcms/polling/bcms-polling.css",
    "public/bcms/polling/bcms-polling.js",
    "rails/init.rb"
  ]
  s.homepage = %q{http://browsercms.org}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{browsercms}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Polling Module for BrowserCMS}
  s.test_files = [
    "test/functional/cms/poll_responses_controller_test.rb",
    "test/functional/cms/polls_controller_test.rb",
    "test/functional/poll_responses_controller_test.rb",
    "test/functional/polls_controller_test.rb",
    "test/performance/browsing_test.rb",
    "test/test_helper.rb",
    "test/unit/helpers/poll_responses_helper_test.rb",
    "test/unit/helpers/polls_helper_test.rb",
    "test/unit/models/poll_response_test.rb",
    "test/unit/models/poll_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

